# Generated by Django 5.0.6 on 2024-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='bw_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans_bw/'),
        ),
    ]
