# Generated by Django 5.0.6 on 2024-07-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0002_scan_bw_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='bw_image',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='uploaded_at',
        ),
    ]
